version: "3.8"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: ./Dockerfile.airflow
  environment:
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey1234567890" # <- 新增這行
  volumes:
    - ./airflow/dags:/opt/airflow/dags
  restart: always
  user: "${AIRFLOW_UID:-50000}:0"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    <<: *airflow-common
    container_name: airflow
    depends_on:
      - postgres
    command: >
      bash -c "
        airflow db upgrade &&
        airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow webserver
      "
    ports:
      - "8080:8080"

  airflow_scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    depends_on:
      - airflow
    command: airflow scheduler

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - mlflow_db
    volumes:
      - ./mlflow_artifacts:/mlflow_artifacts
    user: "1000:1000" # ✅ 使用與主機相同 UID/GID（確保資料夾可寫）
    command: >
      mlflow server 
        --host 0.0.0.0 
        --port 5000 
        --backend-store-uri postgresql://mlflow:mlflow@mlflow_db:5432/mlflow 
        --default-artifact-root /tmp/mlflow

  mlflow_db:
    image: postgres:15
    container_name: mlflow_db
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - ./mlflow_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # 避免跟 airflow 的 postgres:5432 衝突

