FROM apache/airflow:2.10.5-python3.9

USER root
RUN apt-get update && apt-get install -y curl git && apt-get clean

USER airflow
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
